DRAPの実装
virtualCrypto-discord/distream pull request #9
Opened 2021-12-21 12:55 UTC by sizumita

2021-12-21 14:11 UTC, tignear requested changes

2021-12-21 14:11 UTC, tignear commented on drap/src/packet/mod.rs
> +//2^13-1
コメントの位置がおかしい

2021-12-21 14:11 UTC, tignear commented on drap/src/packet/mod.rs
> +//size 13bit + type 3bit
コメントの位置がおかしい

2021-12-22 06:58 UTC, sizumita commented on drap/src/packet/mod.rs
> +//size 13bit + type 3bit
直した

2021-12-22 06:58 UTC, sizumita commented on drap/src/packet/mod.rs
> +//2^13-1
直した

2021-12-23 13:35 UTC, tignear approved these changes

2021-12-24 13:17 UTC, merged